//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUpSchoolProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTestimonial
    {
        public int TestimonialID { get; set; }
        public string NameSurname { get; set; }
        public string City { get; set; }
        public string Profession { get; set; }
        public Nullable<int> Balance { get; set; }
    }
}
